name: Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: npm ci
    - run: npm run build:ci
    - run: npm run test:ci
    - name: Upload builds artifacts
      uses: actions/upload-artifact@v2
      with:
        name: builds
        path: dist/aurelienjames-github-io
        retention-days: 1

#  deploy:
#    runs-on: ubuntu-latest
#    needs: test
