name: Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: npm ci
    - run: npm run build:prod
    - run: npm run test:ci
    - name: Upload builds artifacts
      uses: actions/upload-artifact@v2
      with:
        name: builds
        path: dist/aurelienjames-github-io
        retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Download builds artifacts to be deployed
      uses: actions/download-artifact@v2
      with:
        name: builds
    - name: testing
      run: |
        ls
    - name: Deploy artifacts
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: builds
        FOLDER: builds
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}